### ISSUE TITLE
Cannot enable add-on (no function with name 'texture2D')

### ISSUE THREAD

**Issue by gsoros** [strike-digital/asset_bridge#12]
Hi, when trying to enable the add-on I get:

```
ERROR (gpu.shader): pyGPUShader FragShader: 
      | 
  168 |   vec4 image = texture2D(image, imageUv);
      |                ^
      | Error: no function with name 'texture2D'
      | 
  171 |   image = image * float(compare(imageUv, vec2(.5), .5));
      |           ^
      | `image' used uninitialized

Traceback (most recent call last):
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/__init__.py", line 29, in <module>
    auto_load.init()
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/auto_load.py", line 64, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/auto_load.py", line 69, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/gpu_drawing/shaders.py", line 35, in <module>
    ASSET_PROGRESS_SHADER = load_shader(
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/gpu_drawing/shaders.py", line 32, in load_shader
    return gpu.types.GPUShader(vert_shader, frag_shader)
Exception: Shader Compile Error, see console for more details
```

My system info:
```
====================================
= Blender 3.5.0 System Information =
====================================


Blender:
====================================

version: 3.5.0, branch: blender-v3.5-release, commit date: 2023-03-29 02:56, hash: 1be25cfff18b, type: release
build date: 2023-03-29, 06:35:04
platform: 'Linux-5.19.0-40-generic-x86_64-with-glibc2.36'
binary path: '/home/g/.local/share/blender-3.5.0-linux-x64/blender'
build cflags:  -Wall -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wno-stringop-overread -Wno-stringop-overflow -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
build cxxflags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wno-stringop-overread -Wno-stringop-overflow -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
build linkflags:  -Wl,--version-script='/home/blender/git/blender-v350/blender.git/source/creator/symbols_unix.map'
build system: CMake
windowing environment: 'X11'

Python:
====================================

version: 3.10.9 (main, Feb  9 2023, 04:47:13) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
file system encoding: utf-8:surrogateescape
paths:
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/startup'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/modules'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python310.zip'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/lib-dynload'
	'/home/g/.local/lib/python3.10/site-packages'
	'/home/g/.local/lib/python3.10/site-packages/gpxcsv-0.2.15-py3.10.egg'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/freestyle/modules'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/modules'
	'/home/g/.config/blender/3.5/scripts/addons/modules'
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons'
	'/home/g/.config/blender/3.5/scripts/addons'

Python (External Binary):
====================================

binary path: '/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/bin/python3.10'
version: Python 3.10.9

Directories:
====================================

scripts:
	'/home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts'
	'/home/g/.config/blender/3.5/scripts'
user scripts: '/home/g/.config/blender/3.5/scripts'
pref scripts: None
datafiles: '/home/g/.config/blender/3.5/datafiles'
config: '/home/g/.config/blender/3.5/config'
scripts : '/home/g/.config/blender/3.5/scripts'
autosave: '/home/g/.config/blender/3.5/autosave'
tempdir: '/tmp/blender_Rc2pMJ/'

FFmpeg:
====================================

avcodec:   '59, 37, 100'
avdevice:  '59,  7, 100'
avformat:  '59, 27, 100'
avutil:    '57, 28, 100'
swscale:   ' 6,  7, 100'

SDL:
====================================

Version: 2.24.0
Loading method: dynamically loaded by Blender (WITH_SDL_DYNLOAD=ON)

Other Libraries:
====================================

OpenColorIO:  2,  2,  0
OpenImageIO:  2,  4,  6
OpenShadingLanguage:  1, 13,  0
OpenSubdiv:  3,  5,  0
OpenVDB: 10,  0,  0
Alembic:  1,  8,  3
USD:  0, 22, 11

GPU:
====================================

renderer:	'KABINI (, LLVM 15.0.2, DRM 2.50, 5.19.0-40-generic)'
vendor:		'AMD'
version:	'4.5 (Core Profile) Mesa 22.2.5'
device type:	'AMD'
backend type:	'OPENGL'
extensions:
	GL_AMD_conservative_depth
	GL_AMD_depth_clamp_separate
	GL_AMD_draw_buffers_blend
	GL_AMD_gpu_shader_int64
	GL_AMD_multi_draw_indirect
	GL_AMD_performance_monitor
	GL_AMD_pinned_memory
	GL_AMD_query_buffer_object
	GL_AMD_seamless_cubemap_per_texture
	GL_AMD_shader_stencil_export
	GL_AMD_shader_trinary_minmax
	GL_AMD_texture_texture4
	GL_AMD_vertex_shader_layer
	GL_AMD_vertex_shader_viewport_index
	GL_ANGLE_texture_compression_dxt3
	GL_ANGLE_texture_compression_dxt5
	GL_ARB_ES2_compatibility
	GL_ARB_ES3_1_compatibility
	GL_ARB_ES3_2_compatibility
	GL_ARB_ES3_compatibility
	GL_ARB_arrays_of_arrays
	GL_ARB_base_instance
	GL_ARB_bindless_texture
	GL_ARB_blend_func_extended
	GL_ARB_buffer_storage
	GL_ARB_clear_buffer_object
	GL_ARB_clear_texture
	GL_ARB_clip_control
	GL_ARB_color_buffer_float
	GL_ARB_compressed_texture_pixel_storage
	GL_ARB_compute_shader
	GL_ARB_compute_variable_group_size
	GL_ARB_conditional_render_inverted
	GL_ARB_conservative_depth
	GL_ARB_copy_buffer
	GL_ARB_copy_image
	GL_ARB_cull_distance
	GL_ARB_debug_output
	GL_ARB_depth_buffer_float
	GL_ARB_depth_clamp
	GL_ARB_derivative_control
	GL_ARB_direct_state_access
	GL_ARB_draw_buffers
	GL_ARB_draw_buffers_blend
	GL_ARB_draw_elements_base_vertex
	GL_ARB_draw_indirect
	GL_ARB_draw_instanced
	GL_ARB_enhanced_layouts
	GL_ARB_explicit_attrib_location
	GL_ARB_explicit_uniform_location
	GL_ARB_fragment_coord_conventions
	GL_ARB_fragment_layer_viewport
	GL_ARB_fragment_shader
	GL_ARB_framebuffer_no_attachments
	GL_ARB_framebuffer_object
	GL_ARB_framebuffer_sRGB
	GL_ARB_get_program_binary
	GL_ARB_get_texture_sub_image
	GL_ARB_gl_spirv
	GL_ARB_gpu_shader5
	GL_ARB_gpu_shader_fp64
	GL_ARB_gpu_shader_int64
	GL_ARB_half_float_pixel
	GL_ARB_half_float_vertex
	GL_ARB_instanced_arrays
	GL_ARB_internalformat_query
	GL_ARB_internalformat_query2
	GL_ARB_invalidate_subdata
	GL_ARB_map_buffer_alignment
	GL_ARB_map_buffer_range
	GL_ARB_multi_bind
	GL_ARB_multi_draw_indirect
	GL_ARB_occlusion_query2
	GL_ARB_parallel_shader_compile
	GL_ARB_pipeline_statistics_query
	GL_ARB_pixel_buffer_object
	GL_ARB_point_sprite
	GL_ARB_polygon_offset_clamp
	GL_ARB_program_interface_query
	GL_ARB_provoking_vertex
	GL_ARB_query_buffer_object
	GL_ARB_robust_buffer_access_behavior
	GL_ARB_robustness
	GL_ARB_sample_shading
	GL_ARB_sampler_objects
	GL_ARB_seamless_cube_map
	GL_ARB_seamless_cubemap_per_texture
	GL_ARB_separate_shader_objects
	GL_ARB_shader_atomic_counter_ops
	GL_ARB_shader_atomic_counters
	GL_ARB_shader_ballot
	GL_ARB_shader_bit_encoding
	GL_ARB_shader_clock
	GL_ARB_shader_group_vote
	GL_ARB_shader_image_load_store
	GL_ARB_shader_image_size
	GL_ARB_shader_objects
	GL_ARB_shader_precision
	GL_ARB_shader_stencil_export
	GL_ARB_shader_storage_buffer_object
	GL_ARB_shader_subroutine
	GL_ARB_shader_texture_image_samples
	GL_ARB_shader_texture_lod
	GL_ARB_shader_viewport_layer_array
	GL_ARB_shading_language_420pack
	GL_ARB_shading_language_include
	GL_ARB_shading_language_packing
	GL_ARB_spirv_extensions
	GL_ARB_stencil_texturing
	GL_ARB_sync
	GL_ARB_tessellation_shader
	GL_ARB_texture_barrier
	GL_ARB_texture_buffer_object
	GL_ARB_texture_buffer_object_rgb32
	GL_ARB_texture_buffer_range
	GL_ARB_texture_compression_bptc
	GL_ARB_texture_compression_rgtc
	GL_ARB_texture_cube_map_array
	GL_ARB_texture_filter_anisotropic
	GL_ARB_texture_float
	GL_ARB_texture_gather
	GL_ARB_texture_mirror_clamp_to_edge
	GL_ARB_texture_multisample
	GL_ARB_texture_non_power_of_two
	GL_ARB_texture_query_levels
	GL_ARB_texture_query_lod
	GL_ARB_texture_rectangle
	GL_ARB_texture_rg
	GL_ARB_texture_rgb10_a2ui
	GL_ARB_texture_stencil8
	GL_ARB_texture_storage
	GL_ARB_texture_storage_multisample
	GL_ARB_texture_swizzle
	GL_ARB_texture_view
	GL_ARB_timer_query
	GL_ARB_transform_feedback2
	GL_ARB_transform_feedback3
	GL_ARB_transform_feedback_instanced
	GL_ARB_transform_feedback_overflow_query
	GL_ARB_uniform_buffer_object
	GL_ARB_vertex_array_bgra
	GL_ARB_vertex_array_object
	GL_ARB_vertex_attrib_64bit
	GL_ARB_vertex_attrib_binding
	GL_ARB_vertex_buffer_object
	GL_ARB_vertex_shader
	GL_ARB_vertex_type_10f_11f_11f_rev
	GL_ARB_vertex_type_2_10_10_10_rev
	GL_ARB_viewport_array
	GL_ATI_blend_equation_separate
	GL_ATI_meminfo
	GL_ATI_texture_float
	GL_ATI_texture_mirror_once
	GL_EXT_EGL_image_storage
	GL_EXT_EGL_sync
	GL_EXT_abgr
	GL_EXT_blend_equation_separate
	GL_EXT_demote_to_helper_invocation
	GL_EXT_depth_bounds_test
	GL_EXT_draw_buffers2
	GL_EXT_draw_instanced
	GL_EXT_framebuffer_blit
	GL_EXT_framebuffer_multisample
	GL_EXT_framebuffer_multisample_blit_scaled
	GL_EXT_framebuffer_object
	GL_EXT_framebuffer_sRGB
	GL_EXT_memory_object
	GL_EXT_memory_object_fd
	GL_EXT_packed_depth_stencil
	GL_EXT_packed_float
	GL_EXT_pixel_buffer_object
	GL_EXT_polygon_offset_clamp
	GL_EXT_provoking_vertex
	GL_EXT_shader_image_load_formatted
	GL_EXT_shader_image_load_store
	GL_EXT_shader_integer_mix
	GL_EXT_shader_samples_identical
	GL_EXT_texture_array
	GL_EXT_texture_compression_dxt1
	GL_EXT_texture_compression_rgtc
	GL_EXT_texture_compression_s3tc
	GL_EXT_texture_filter_anisotropic
	GL_EXT_texture_integer
	GL_EXT_texture_mirror_clamp
	GL_EXT_texture_sRGB
	GL_EXT_texture_sRGB_R8
	GL_EXT_texture_sRGB_decode
	GL_EXT_texture_shadow_lod
	GL_EXT_texture_shared_exponent
	GL_EXT_texture_snorm
	GL_EXT_texture_swizzle
	GL_EXT_timer_query
	GL_EXT_transform_feedback
	GL_EXT_vertex_array_bgra
	GL_EXT_vertex_attrib_64bit
	GL_EXT_window_rectangles
	GL_IBM_multimode_draw_arrays
	GL_INTEL_blackhole_render
	GL_KHR_blend_equation_advanced
	GL_KHR_context_flush_control
	GL_KHR_debug
	GL_KHR_no_error
	GL_KHR_parallel_shader_compile
	GL_KHR_robust_buffer_access_behavior
	GL_KHR_robustness
	GL_KHR_texture_compression_astc_ldr
	GL_KHR_texture_compression_astc_sliced_3d
	GL_MESA_framebuffer_flip_y
	GL_MESA_pack_invert
	GL_MESA_shader_integer_functions
	GL_MESA_texture_signed_rgba
	GL_NVX_gpu_memory_info
	GL_NV_alpha_to_coverage_dither_control
	GL_NV_compute_shader_derivatives
	GL_NV_conditional_render
	GL_NV_copy_image
	GL_NV_depth_clamp
	GL_NV_packed_depth_stencil
	GL_NV_shader_atomic_int64
	GL_NV_texture_barrier
	GL_NV_vdpau_interop
	GL_OES_EGL_image
	GL_S3_s3tc

Implementation Dependent GPU Limits:
====================================

Maximum Batch Vertices:	3000
Maximum Batch Indices:	3000

GLSL:
Maximum Varying Floats:	128
Maximum Vertex Attributes:	16
Maximum Vertex Uniform Components:	16384
Maximum Fragment Uniform Components:	16384
Maximum Vertex Image Units:	32
Maximum Fragment Image Units:	32
Maximum Pipeline Image Units:	192

Features:
Compute Shader Support:               	1
Shader Storage Buffer Objects Support:	1
Image Load/Store Support:             	1

Cycles:
====================================


CPU device capabilities: SSE2 SSE41

oneAPI device capabilities:

Enabled add-ons:
====================================

io_anim_bvh (version: (1, 0, 1), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_anim_bvh/__init__.py)
io_curve_svg (version: (), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_curve_svg/__init__.py)
io_mesh_ply (version: (2, 2, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_mesh_ply/__init__.py)
io_mesh_stl (version: (1, 1, 3), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_mesh_stl/__init__.py)
io_mesh_uv_layout (version: (1, 1, 5), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_mesh_uv_layout/__init__.py)
io_scene_fbx (version: (4, 37, 5), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_scene_fbx/__init__.py)
io_scene_gltf2 (version: (3, 5, 30), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_scene_gltf2/__init__.py)
io_scene_obj (version: (3, 9, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_scene_obj/__init__.py)
io_scene_x3d (version: (2, 3, 1), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/io_scene_x3d/__init__.py)
cycles (version: (), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/cycles/__init__.py)
pose_library (version: (2, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/pose_library/__init__.py)
materials_library_vx (version: (0, 6, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/materials_library_vx/__init__.py)
materials_utils (version: (2, 2, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/materials_utils/__init__.py)
render_povray (version: (0, 1, 3), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/render_povray/__init__.py)
render_ui_animation_render (version: (0, 1, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/render_ui_animation_render.py)
space_view3d_3d_navigation (version: (1, 2, 6), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/space_view3d_3d_navigation.py)
camera_turnaround (version: (0, 3, 0), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/camera_turnaround.py)
sun_position (version: (3, 2, 2), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/sun_position/__init__.py)
lighting_tri_lights (version: (0, 1, 4), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/lighting_tri_lights.py)
precision_drawing_tools (version: (1, 5, 3), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/precision_drawing_tools/__init__.py)
lighting_dynamic_sky (version: (1, 0, 6), path: /home/g/.local/share/blender-3.5.0-linux-x64/3.5/scripts/addons/lighting_dynamic_sky.py)
```

**Comment by strike-digital** [comment]
Ah, thanks for reporting that, turns out I left an unused bit of the code in there that broke in 3.5 for linux users, I uploaded a new release, and it should be fixed there :)

**Comment by gsoros** [comment]
Thanks for the quick response! I was able to enable the new version and set the Library Path, however when clicking the "Check for New Assets..." button I get an error (although the internet connection is fine):

```
Traceback (most recent call last):
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/vendor/requests/adapters.py", line 352, in send
    resp = conn.urlopen(method=request.method, url=url, body=request.body, headers=request.headers, redirect=False, assert_same_host=False, preload_content=False, decode_content=False, retries=self.max_retries, timeout=timeout)
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=0.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/helpers/btypes.py", line 329, in invoke
    retval = _self.execute(context)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/operators/op_check_for_new_assets.py", line 24, in execute
    if not check_internet():
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/helpers/general.py", line 78, in check_internet
    _ = requests.head(url, timeout=timeout)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/vendor/requests/api.py", line 89, in head
    return request('head', url, **kwargs)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/vendor/requests/api.py", line 54, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/vendor/requests/sessions.py", line 302, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/vendor/requests/sessions.py", line 395, in send
    r = adapter.send(request, **kwargs)
  File "/home/g/.config/blender/3.5/scripts/addons/asset_bridge/vendor/requests/adapters.py", line 395, in send
    raise ReadTimeout(e, request=request)
asset_bridge.vendor.requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=0.1)
Error: Python: Traceback (most recent call last):
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/g/.local/share/blender-3.5.0-linux-x64/3.5/python/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
```

**Comment by strike-digital** [comment]
Huh, that's really weird, that seems to be saying that you don't have an internet connection, but I guess that's not accurate 😅

I'll do some research and see if I can find what's causing that

**Comment by gsoros** [comment]
Thanks, could it be that the timeout value of 0.1 is too short?

**Comment by gsoros** [comment]
With the timeout value increased to 5 [here](https://github.com/strike-digital/asset_bridge/blob/1c9767485f3b9f71f52991a5f48fb2a0b709070e/asset_bridge/helpers/general.py#L71) it is working fine. Thanks for your efforts!

**Comment by strike-digital** [comment]
Perfect, I'll update that in the code, and it should be in the next release :)
