### ISSUE TITLE
Addon crashes on "check for new assets" 

### ISSUE THREAD

**Issue by chrymium** [strike-digital/asset_bridge#13]
here's what blender (3.5, latest asset bridge version) tells me:

bpy.data.window_managers["WinMan"].addon_search = "asse"
bpy.ops.asset_bridge.report_message(severity="ERROR", message="Can't check for new assets, no internet connection detected")
Can't check for new assets, no internet connection detected
bpy.ops.asset_bridge.check_for_new_assets(auto_download=True)
Python: Traceback (most recent call last):
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\vendor\requests\adapters.py", line 352, in send
    resp = conn.urlopen(method=request.method, url=url, body=request.body, headers=request.headers, redirect=False, assert_same_host=False, preload_content=False, decode_content=False, retries=self.max_retries, timeout=timeout)
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\CHRIS\Downloads\blender-3.5.0-windows-x64\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=0.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\helpers\btypes.py", line 329, in invoke
    retval = _self.execute(context)
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\operators\op_check_for_new_assets.py", line 24, in execute
    if not check_internet():
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\helpers\general.py", line 78, in check_internet
    _ = requests.head(url, timeout=timeout)
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\vendor\requests\api.py", line 89, in head
    return request('head', url, **kwargs)
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\vendor\requests\api.py", line 54, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\vendor\requests\sessions.py", line 302, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\vendor\requests\sessions.py", line 395, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\vendor\requests\adapters.py", line 395, in send
    raise ReadTimeout(e, request=request)
asset_bridge.vendor.requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=0.1)

bpy.ops.view3d.blenderkit_disclaimer_widget(message="Please rate responsively and plentifully. This helps us distribute rewards to the authors.", url="https://www.blenderkit.com/docs/rating/", fadeout_time=8, tip=True)

**Comment by strike-digital** [comment]
Hi, this should be fixed in the latest release, could you test it out and make sure that it works?

Thanks!

**Comment by chrymium** [comment]
addon works as expected! thank you very much

**Comment by strike-digital** [comment]
Great, glad it's working!
