### ISSUE TITLE
FileNotFoundError when setting up addon.

### ISSUE THREAD

**Issue by ksyuc** [strike-digital/asset_bridge#14]
Version: git
Blender version: 3.5

I enabled the addon in the blender preferences, but when I set the library path, it gave this error.
(The path in the error is not the library path I chose.)

Manually creating the "/cache/previews/" directory under "addons/asset_bridge" seemed to fix it.

```
Traceback (most recent call last):
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 83, in lib_path_set
    DIRS.update(new_path)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/constants.py", line 92, in update
    with open(FILES.prefs, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blender/3.5/scripts/addons/asset_bridge/cache/prefs.json'
File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 34, in lib_path_set
Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/startup/bl_ui/space_userpref.py", line 2092, in draw
    draw(context)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 214, in draw
    new_assets_available = lists_obj.new_assets_available()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/api.py", line 113, in new_assets_available
    preview_files = os.listdir(DIRS.previews)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blender/3.5/scripts/addons/asset_bridge/cache/previews'
Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/startup/bl_ui/space_userpref.py", line 2092, in draw
    draw(context)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 214, in draw
    new_assets_available = lists_obj.new_assets_available()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/api.py", line 113, in new_assets_available
    preview_files = os.listdir(DIRS.previews)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blender/3.5/scripts/addons/asset_bridge/cache/previews'
Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/startup/bl_ui/space_userpref.py", line 2092, in draw
    draw(context)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 214, in draw
    new_assets_available = lists_obj.new_assets_available()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/api.py", line 113, in new_assets_available
    preview_files = os.listdir(DIRS.previews)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blender/3.5/scripts/addons/asset_bridge/cache/previews'
Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/startup/bl_ui/space_userpref.py", line 2092, in draw
    draw(context)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 214, in draw
    new_assets_available = lists_obj.new_assets_available()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/api.py", line 113, in new_assets_available
    preview_files = os.listdir(DIRS.previews)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blender/3.5/scripts/addons/asset_bridge/cache/previews'
```

**Comment by strike-digital** [comment]
Hi, thanks for reporting that, I'm pretty sure I know what's causing it.
If that is the problem then you should be able to fix it by just creating the missing directory and re starting Blender.

Unfortunately though, I'm away from my computer for the next couple of weeks, so I won't be able to make any fixes to the actual code until then.

Thanks for pointing it out though, it'll be at the top of my list when I get back :)
