### ISSUE TITLE
AttributeError when downloading previews.

### ISSUE THREAD

**Issue by ksyuc** [strike-digital/asset_bridge#15]
Version: git
Blender version: 3.5

I clicked "Download Previews" in Blender user preferences.
The previews downloaded (I can see them on disk), but just as the download finished it gave an error.

This was in the terminal.
```
Initialization for ambient_cg took 0.10s
Initialization for poly_haven took 0.07s
Traceback (most recent call last):
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/operators/op_create_dummy_assets.py", line 29, in execute
    ensure_bl_asset_library_exists()
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/helpers/library.py", line 30, in ensure_bl_asset_library_exists
    if asset_lib.path == str(DIRS.dummy_assets):
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Dirs' object has no attribute 'dummy_assets'
Error: Python: Traceback (most recent call last):
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/operators/op_create_dummy_assets.py", line 29, in execute
    ensure_bl_asset_library_exists()
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/helpers/library.py", line 30, in ensure_bl_asset_library_exists
    if asset_lib.path == str(DIRS.dummy_assets):
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Dirs' object has no attribute 'dummy_assets'
Location: /usr/share/blender/3.5/scripts/modules/bpy/ops.py:113
Traceback (most recent call last):
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/helpers/main_thread.py", line 16, in main_thread_timer
    func(*args, **kwargs)
  File "/usr/share/blender/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/operators/op_create_dummy_assets.py", line 29, in execute
    ensure_bl_asset_library_exists()
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/helpers/library.py", line 30, in ensure_bl_asset_library_exists
    if asset_lib.path == str(DIRS.dummy_assets):
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Dirs' object has no attribute 'dummy_assets'
Location: /usr/share/blender/3.5/scripts/modules/bpy/ops.py:113

Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/startup/bl_ui/space_userpref.py", line 2092, in draw
    draw(context)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 247, in draw
    dummy_blends = [f for f in DIRS.dummy_assets.iterdir() if f.suffix == ".blend"]
                               ^^^^^^^^^^^^^^^^^
AttributeError: 'Dirs' object has no attribute 'dummy_assets'
Info: Downloaded 2972 asset previews in 114.18s

Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/startup/bl_ui/space_userpref.py", line 2092, in draw
    draw(context)
  File "/home/user/.config/blender/3.5/scripts/addons/asset_bridge/preferences.py", line 247, in draw
    dummy_blends = [f for f in DIRS.dummy_assets.iterdir() if f.suffix == ".blend"]
                               ^^^^^^^^^^^^^^^^^
AttributeError: 'Dirs' object has no attribute 'dummy_assets'
```

**Comment by strike-digital** [comment]
Hi, really sorry for the wait, are you still having this issue?
