### ISSUE TITLE
Cant active on blender 4.0

### ISSUE THREAD

**Issue by FidoAnh** [strike-digital/asset_bridge#17]
this is in my console:
addon_utils.disable: asset_bridge not disabled
Modules Installed (asset_bridge) from 'C:\\Users\\FidoTran\\Downloads\\asset_bridge_2_2_0_blender.4.0_(1).zip' into 'C:\\Users\\FidoTran\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "C:\FidoSoftware\blender-4.0.0\4.0\scripts\startup\bl_ui\space_userpref.py", line 2300, in draw
    draw(context)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\preferences.py", line 219, in draw
    wrap_text(context, message, box)
  File "C:\Users\FidoTran\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_bridge\ui\ui_helpers.py", line 72, in wrap_text
    blf.size(0, 11, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)

**Comment by strike-digital** [comment]
Hey sorry for the wait, been pretty busy recently, this should be fixed now :)
