### ISSUE TITLE
Error importing asset ph_aerial_beach_01

### ISSUE THREAD

**Issue by yahyako** [strike-digital/asset_bridge#21]
Error importing asset ph_aerial_beach_01:
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/4.1/scripts/addons/asset_bridge/helpers/assets.py", line 197, in import_asset
imported = asset.import_asset(context)
ААААЛ
АААААААААААААЛАЛ
File "/Applications/Blender.app/Contents/Resources/4.1/scripts/addons/asset_bridge/apis/polyhaven/ph_asset.py", line 136, in import_asset
mat = import_material(texture_files, self import_name, link_method=self.link_method)
АААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААЛАЛ
File "/Applications/Blender.app/Contents/Resources/4.1/scripts/addons/asset_bridge/apis/asset_utils.py", line 252, in import_material
bsdf_node = nodes["Principled BSDF"]
~ANNaAAAAAAAAAAAAAAAAAAA
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'
<img width="822" alt="iShot_2024-05-03_10 27 23" src="https://github.com/strike-digital/asset_bridge/assets/76864710/11b35578-f992-468a-8059-fbebf46c3d5a">

**Comment by yahyako** [comment]
"I recently started learning Blender and came across ASSET BRIDGE on YouTube, which is awesome. I followed the tutorial and managed to install it, but while I can import models, I'm having trouble using surface and HDR environment maps by drag and drop. I would appreciate your help if possible. Thank you."
